### ISSUE TITLE
use with powerline

### ISSUE THREAD

**Issue by facundoolano** [oneKelvinSmith/monokai-emacs#71]
Hi! I just started to use prelude with this theme, and I've been trying to add powerline as well. I tried powerline, spaceline and smart-mode-line-powerline-theme, but none of them look good. For example, with powerline:

<img width="473" alt="screen shot 2016-12-23 at 3 12 40 pm" src="https://cloud.githubusercontent.com/assets/1040941/21533630/4e9714a6-cd3b-11e6-9407-e1e80db260e9.png">

Is there something I can tune to make them play together?

**Comment by oneKelvinSmith** [comment]
This is an issue with how emacs renders the powerline separators (see https://github.com/milkypostman/powerline/issues/99). The separators are not rendered with `srgb` colours.

One possible solution is to tell emacs not to use `srgb` colours:

```lisp
(setq ns-use-srgb-colorspace nil)
```

I don't like this because it looks washed out.

What I do is use a ligatured font like https://github.com/tonsky/FiraCode and tell powerline to use `utf8` separator with:

```lisp
(setq powerline-default-separator 'utf-8)
```

In the `init.el` (or equivalent) initialisation file.

**Comment by facundoolano** [comment]
Ok, you pointed me in the right direction, thanks! I didn't like the srgb fix either, but found that installing another version of emacs for mac does the trick.
